languageCode = "en-us"
title = "SportDx API Documentation"
baseURL = "http://apidocs.sportdx.github.com/"
canonifyURLs = true

theme = "docuapi"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

publishDir = "../"

[params]
search = true
  
# Configure the language example tabs.
#[[params.language_tabs]]
#key = "go"
#name = "Go" 
[[params.language_tabs]]
key = "shell"
name = "Shell" 
#[[params.language_tabs]]
#key = "ruby"
#name = "Ruby"
#[[params.language_tabs]]
#key = "python"
#name = "Python"
#[[params.language_tabs]]
#key = "javascript"
#name = "Javascript"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "SportDx API Documentation"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Sign Up for a Developer Key</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Copyright SportDx Inc. All Rights Reserved."
]
